[project]
name = "excel-quotation-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "torch>=2.7.0",
    "transformers>=4.52.3",
    "xlrd>=2.0.1",
]
